<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>gongwei-admin</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GongWei.Infrastructure\GongWei.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

</Project>
